version: "3.9"

services:
  app:
    build: .
    container_name: finalsite_app
    command: uvicorn main:app --host 0.0.0.0 --port 8041
    env_file:
      - .env
    expose:
      - "8041"
    restart: unless-stopped
    networks:
      - investstroi_net

networks:
  investstroi_net:
    external: true
    name: investstroi_default